name: 'Packages Split'

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  packages_split:
    name: "Packages Split"
    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        # define package to repository map
        package:
          -
            local_path: 'split-a'
            split_repository: 'test-monorepo-split-a'
          -
            local_path: 'split-b'
            split_repository: 'test-monorepo-split-b'

    steps:
      - uses: actions/checkout@v2

      # on branches
      -
        if: "!startsWith(github.ref, 'refs/tags/')"
        shell: bash
        run: |
          ./bin/split-branch.sh ${GITHUB_REF}

      # on tags
      -
        if: "startsWith(github.ref, 'refs/tags/')"
        shell: bash
        run: |
          ./bin/split-tag.sh ${GITHUB_REF#refs/tags/}
