name: 'Packages Split'

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  packages_split:
    name: "Packages Split"
    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        # define package to repository map
        package:
          -
            local_path: 'split-a'
            split_repository: 'test-monorepo-split-a'
          -
            local_path: 'split-b'
            split_repository: 'test-monorepo-split-b'

    steps:
      -   uses: actions/checkout@v2

      # on branches
      -
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/monorepo-split-github-action@2.1"
        with:
          package_directory: 'packages/${{ matrix.package.local_path }}'
          repository_organization: 'yann-eugone'
          repository_name: '${{ matrix.package.split_repository }}'
          user_name: "GitHub Action"
          user_email: "action@github.com"
          branch: "main"

      # on tags
      -
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/monorepo-split-github-action@2.1"
        with:
          tag: ${GITHUB_REF#refs/tags/}

          package_directory: 'packages/${{ matrix.package.local_path }}'
          repository_organization: 'yann-eugone'
          repository_name: '${{ matrix.package.split_repository }}'
          user_name: "GitHub Action"
          user_email: "action@github.com"
          branch: "main"
